name: Python News application test with GitHub Actions

on: [push]  # This line tells GitHub to run the workflow anytime code is pushed to the repository

jobs:
  build:

    runs-on: ubuntu-latest   # This line specifies that the job will run on an Ubuntu Linux runner. GitHub provides runners for Linux, Windows, and macOS

    steps:  # This is where you specify the steps that the job will run
    - uses: actions/checkout@v2  # This step checks out a copy of your repository
    - name: Set up Python 3.10.6 # This step sets up a Python environment on the runner
      uses: actions/setup-python@v2  # This step sets up a Python environment on the runner
      with:
        python-version: 3.10.6
    - name: Install dependencies  # This step installs any dependencies your project needs
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8  # This step runs flake8 to check your Python syntax
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check formatting with black  # This step runs black to check your Python formatting
      run: |
        pip install black
        black --check .
    - name: Check docstrings with pydocstyle  # This step runs pydocstyle to check your docstrings
      run: |
        pip install pydocstyle
        pydocstyle .
